apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
        release: {{ .Release.Name }}
spec:
    replicas: {{ .Values.replicas }}
    selector:
      matchLabels:
        app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: bitnami/postgresql:latest
                  imagePullPolicy: "IfNotPresent"
                  ports:
                      - containerPort: {{ .Values.port }}
                  env:
                      - name: POSTGRES_DB
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretName }}
                                key: POSTGRES_DB
                      - name: POSTGRES_USER
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretName }}
                                key: POSTGRES_USER
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: {{ .Values.secretName }}
                                key: POSTGRES_PASSWORD
                  volumeMounts:
                      - mountPath: {{ .Values.mountPath }}
                        name: postgredb
            volumes:
                - name: postgredb
                  persistentVolumeClaim:
                      claimName: {{ .Values.claimName }}

