apiVersion: v1
kind: Secret
metadata:
    name: {{ .Values.secretName }}
type: Opaque
data:
    POSTGRES_DB: cG9zdGdyZXNkYg==
    POSTGRES_USER: cG9zdGdyZXNhZG1pbg==
    POSTGRES_PASSWORD: YWRtaW4xMjM=
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.volumeName }}
    labels:
        type: local
        app: postgres
spec:
    storageClassName: manual
    capacity:
        storage: {{ .Values.storageSize }}
    accessModes:
        - ReadWriteMany
    hostPath:
        path: {{ .Values.storagePath }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.claimName }}
    labels:
        app: postgres
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: {{ .Values.storageSize }}
