apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mxe-node
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: mxe-node
        type: mxe
    spec:
      containers:
        - name: mxe-node
          image: mxe-node-api-express
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
