apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deployment
  labels:
    app: {{ .Values.name }}
    release: {{ .Release.Name }}
spec:
    replicas: {{ .Values.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.name }}
    template:
      metadata:
        labels:
          app: {{ .Values.name }}
          appType: {{ .Values.appType }}
      spec:
        containers:
          - name: {{ .Values.name }}
            image: {{ .Values.image }}
            imagePullPolicy: "{{ .Values.imagePullPolicy }}"
            env:
              - name: MONGODB_HOST
                value: {{ .Values.mongodb.hostdns }}
              - name: MONGODB_PORT
                value: {{ .Values.mongodb.port | quote}}
              - name: MONGODB_DBNAME
                value: {{ .Values.mongodb.dbname }}
            ports:
              - containerPort: {{ .Values.containerPort }}
