apiVersion: v1
kind: PersistentVolume
metadata:
    name: {{ .Values.volumeName }}
    labels:
        type: local
        app: mongodb
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: {{ .Values.storageSize }}
    hostPath:
        path: {{ .Values.storagePath }}
        type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.claimName }}
    labels:
        app: mongodb
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: {{ .Values.storageSize }}
