apiVersion: v1
kind: Service
metadata:
    name: mongodb
    labels:
        app: mongodb
        release: {{ .Release.Name }}
spec:
    ports:
        - port: {{ .Values.port }}
          protocol: TCP
    selector:
        app: mongodb
